### ISSUE TITLE
Organizations Doc Update 

### ISSUE THREAD

**Issue by JQTNguyen** [pantheon-systems/documentation#7497] opened 2022-07-14 12:25 UTC
Re: [Organizations](https://pantheon.io/docs/organizations)

Priority: Low

## Issue Description:

This does not appear to be true:

"Team members of a site who are not members of the supporting organization will not have access to Multidev environments"

1. My personal account is a Team Member on the badcamp-2020 website.
2. It is not a member of the Owning Org.
3. It is not a member of the Supporting Org.
4. I can still access and create Multidevs.

![Pasted_Image_7_14_22__5_19_AM](https://user-images.githubusercontent.com/3485338/178981807-cc289134-cf27-45bf-b5f2-f61fb7bd0415.png)

## Suggested Resolution

Validate and update.

**Comment by EdwardAngert** [comment] 2022-07-14 17:45
nice find, @JQTNguyen !
@whitneymeredith , can you check with @ivoverus to confirm whether or not this is intended behavior?

**Comment by EdwardAngert** [comment] 2022-07-14 18:04
my mistake, @whitneymeredith  - I read that wrong
I'll DM you the Slack thread where it's confirmed

**Comment by whitneymeredith** [comment] 2022-07-19 15:50
@ivoverus confirmed that the owner org is Gold. That means all users that support sites owned by this Gold org will have access to create Multidev instances. I added a note to the [new Multidev Guide ](https://pr-7501--pantheon-docs.my.pantheonfrontend.website/docs/guides/multidev) currently in progress to help clarify the logic. Closing #7501 will also close this issue.

**Closed** 2022-07-25 17:36 UTC
Labels: Fix Content, Pantheor
