### ISSUE TITLE
Metrics in the Site Dashboard Doc Update 

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#3565] opened 2018-04-13 19:25 UTC
Re: [Metrics in the Site Dashboard](https://pantheon.io/docs/metrics/)

Priority (Low‚ Medium‚ High):

## Issue Description:
FAQ: **Can I see metrics for other environments?** will be stale on next cut of Terminus (whatever is released after 1.8)

## Suggested Resolution
Once new release is cut for Terminus, update installation method to something like: 
> [Install Terminus](/docs/terminus/install/) or update to the <a href="/docs/terminus/updates#update-to-the-current-release-" data-proofer-ignore>current release</a> for access to the `alpha:metrics` command.

Currently this is bleeding edge functionality - before updating, confirm that you can see metrics for all envs via normal install method

**Comment by rachelwhitton** [comment] 2018-06-11 15:52
Terminus 1.8.1 was released but I have not been able to update in order to confirm the state of metrics command. Leaving this issue blocked

**Comment by alexfornuto** [comment] 2018-07-27 13:58
Confirmed that 1.8.1 still requires the `alpha` prefix.

**Comment by alexfornuto** [comment] 2018-10-30 23:17
Update: Terminus 1.9.0 _still_ requires the `alpha` prefix. The command itself changed to `alpha:env:metrics`, but  `alpha:metrics` still works, so I see no reason to update to an intermediary form.

**Comment by alexfornuto** [comment] 2019-02-25 17:52
Closing, to be re-opened when `CORE-344` is updated.

**Comment by greg-1-anderson** [comment] 2019-05-06 22:48
`CORE-344` is scheduled for this sprint.

**Comment by greg-1-anderson** [comment] 2019-05-08 22:38
The `metrics` command can now be used without the `alpha:` prefix in the latest development version of Terminus. This command will be generally available after the next Terminus stable release.

**Comment by eabquina** [comment] 2019-07-05 08:02
Tested this in Terminus 2.0.1 but we're not yet able to use it without the `alpha` metrics

```
$ terminus --version
Terminus 2.0.1

$ terminus metrics --help

  Command "metrics" is not defined.
  Did you mean one of these?
      alpha:env:metrics
      alpha:metrics
```

Is it because it was reverted here?
https://github.com/pantheon-systems/terminus/commit/cd940e07ebd95c7e4036125f22fe90bc6bf0be4c?

And this means it wasn't really deployed yet?

**Comment by alexfornuto** [comment] 2019-07-09 14:51
@eabquina it was deployed into the master branch, so it will be in the next build made from that branch. I assume 2.0.1 was versioned before this merge. I expect it will come with 2.0.2, but @greg-1-anderson can (hopefully) confirm that.

**Closed** 2019-10-01 21:33 UTC
Labels: In Progress, Product
