### ISSUE TITLE
"Failed - No file" upon clicking button to download script - GoAccess doc

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#5021] opened 2019-08-14 11:10 UTC
Re: [Parsing nginx Access Logs with GoAccess](https://pantheon.ionginx-access-log)

Priority: Low 

## Issue Description: 
In this section: https://pantheon.io/docs/nginx-access-log#automate-goaccess-reports

Click the "download script" button 

File is not created as expected

![Screen Shot 2019-08-14 at 6 05 09 AM](https://user-images.githubusercontent.com/10119525/63016751-1dee4780-be5a-11e9-89a4-2f9c08027c83.png)

## Suggested Resolution

Perhaps a JS bug? No direct resolution to suggest

**Comment by alexfornuto** [comment] 2019-08-14 15:33
Closing as a duplicate of #5012

**Closed by alexfornuto** 2019-08-14 15:33 UTC
Labels: CSM
