### ISSUE TITLE
Terminus Manual Install & Version Updates

### ISSUE THREAD

**Issue by cityofoaksdesign** [pantheon-systems/documentation#3399] opened 2018-02-20 18:35 UTC
Re: https://pantheon.io/docs/terminus/install/
## Issue Description
New (novice) users wanting to install Terminus may not be familiar with the [terminus github page](https://github.com/pantheon-systems/terminus) and therefore may not be aware there are actually three other ways in which to install and update Terminus which may be better suited to their workflow. 

## Suggested Resolution

Add the additional install methods to the Terminus Manual ['Install' tab](https://pantheon.io/docs/terminus/install/) via an accordion
(_or simply reference the [github page](https://github.com/pantheon-systems/terminus#installation) for additional install methods_)

EXPLORE ADVANCED INSTALL METHODS (OPTIONAL) -- > Accordion
- [Installing with Composer](https://github.com/pantheon-systems/terminus#installing-with-composer)
- [Installing with Homebrew (for Macs)](https://github.com/pantheon-systems/terminus#installing-with-homebrew-for-macs)
- [Installing with Git](https://github.com/pantheon-systems/terminus#installing-with-git)

Add the additional update methods to the Terminus Manual ['Version Updates' tab](https://pantheon.io/docs/terminus/updates/) via an accordion
(_or simply reference the [github page](https://github.com/pantheon-systems/terminus#updating) for additional update methods_)

EXPLORE ADVANCED UPDATE METHODS (OPTIONS) -- > Accordion 
- [Updating with Composer](https://github.com/pantheon-systems/terminus#updating-with-composer)
- [Updating with Homebrew (for Macs)](https://github.com/pantheon-systems/terminus#updating-with-homebrew-for-macs)
- [Updating with Git](https://github.com/pantheon-systems/terminus#updating-with-git)

For a live example of the accordion, see https://pantheon.io/docs/terminus/plugins/

**Comment by alexfornuto** [comment] 2018-03-19 14:57
Closing as a duplicate of #3398, to be addressed in the same PR.

**Closed by alexfornuto** 2018-03-19 14:57 UTC
Labels: External
