### ISSUE TITLE
Launch Essentials Doc Update 

### ISSUE THREAD

**Issue by greg-1-anderson** [pantheon-systems/documentation#2815] opened 2017-08-17 23:06 UTC
Re: [Launch Essentials](https://pantheon.io/docs/guides/launch/redirects/)

Priority (Low‚ Medium‚ High): Low

## Issue Description:
The sample code in the "WordPress" tab to redirect is in conflict with the boilerplate code shipped in pantheon-systems/WordPress

## Suggested Resolution 
Really, I think we need to clean up wp-config.php in the source repository. Prior to that, we should probably add a note that the code suggested on the page should *replace* the boilerplate code in wp-config.php.

The code to replace is:
```
/** A couple extra tweaks to help things run well on Pantheon. **/
    if (isset($_SERVER['HTTP_HOST'])) {
        // HTTP is still the default scheme for now. 
        $scheme = 'http';
        // If we have detected that the end use is HTTPS, make sure we pass that
        // through here, so <img> tags and the like don't generate mixed-mode
        // content warnings.
        if (isset($_SERVER['HTTP_USER_AGENT_HTTPS']) && $_SERVER['HTTP_USER_AGENT_HTTPS'] == 'ON') {
            $scheme = 'https';
        }
        define('WP_HOME', $scheme . '://' . $_SERVER['HTTP_HOST']);
        define('WP_SITEURL', $scheme . '://' . $_SERVER['HTTP_HOST']);
    }
```

@ataylorme or @stevector please review.

**Comment by alexfornuto** [comment] 2017-08-18 16:39
@greg-1-anderson This is a duplicate of #2405. I'm closing this issue, but feel free to add to the discussion there.

**Closed by alexfornuto** 2017-08-18 16:39 UTC
Labels: fix content
