### ISSUE TITLE
Cron for Drupal Doc Update 

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#3068] opened 2017-11-07 19:19 UTC
Re: [Cron for Drupal](https://pantheon.io/docs/drupal-cron/)

Priority (Low‚ Medium‚ High):

## Issue Description:
Didn't we have a section on how to set up custom cron jobs once? With Elysia I believe?
Can we get that back / added?

Ref: 
Ticket 93439

## Suggested Resolution

**Comment by alexfornuto** [comment] 2017-11-13 16:19
Duplicate of #2591

**Closed by alexfornuto** 2017-11-13 16:19 UTC
Labels: fix content
