### ISSUE TITLE
Create account verification questions 

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#390] opened 2015-04-20 16:36 UTC
Story:
As an Account Holder, I want account verification questions so that I know I'm going to have to work it out myself

we are getting more account verification questions.

In most cases the requests are probably genuine but we can NOT validate who anyone is and should NOT try. Churn happens in orgs but if the request is legit it is possible for them to work this out internally and validate or take control themselves.

We should get a doc page so CSE or SDRs can just point people to the there

--submitted by Timani

 Suzanne A. commented
I think that the account verification page should mention that ownership is important. Just as you should own your own domain in your own name with a permanently reachable email, you should own your site in your own name with a permanently reachable email. We should make it clear, right off the bat, that Pantheon will NEVER transfer ownership of a site from one owner to another, and this is a self-service option.

**Comment by rachelwhitton** [comment] 2015-04-27 20:01
Duplicate of #373 Closing issue and migrating comments.

**Closed by rachelwhitton** 2015-04-27 20:01 UTC
Labels: type: new article
