### ISSUE TITLE
Using a Third Party CDN Doc Update 

### ISSUE THREAD

**Issue by alexdicianu** [pantheon-systems/documentation#3045] opened 2017-10-30 07:49 UTC
Re: [Using a Third Party CDN](https://pantheon.io/docs/third-party-cdns/)

Document the use if `$_SERVER['HTTP_FASTLY_SSL']` according to ticket id #90563

Priority (Low‚ Medium‚ High):
low

## Issue Description:
It seems there's a redirect loop when clients have their own Fastly account.

## Suggested Resolution 
Introduce the use of `$_SERVER['HTTP_FASTLY_SSL']` in the redirect snippet. Needs testing as there is a known issue here described in BUGS-1396

**Comment by alexfornuto** [comment] 2017-10-30 14:53
Duplicate of #3044

**Closed by alexfornuto** 2017-10-30 14:53 UTC
Labels: fix content
