### ISSUE TITLE
Terminus Manual Doc Update 

### ISSUE THREAD

**Issue by rubelyn** [pantheon-systems/documentation#5020] opened 2019-08-14 05:48 UTC
Re: [Terminus Manual](https://pantheon.io/terminus/examples)

Priority: Low

## Issue Description:

Unable to download the reset-dev-to-live.sh bash script.
https://pantheon.io/docs/terminus/examples#reset-dev-environment-to-live

Seeing errors in the browser console:

<img width="538" alt="a" src="https://user-images.githubusercontent.com/14119666/62997043-84df2100-be99-11e9-8c58-51ede9133660.png">

## Suggested Resolution

Fix the error

**Comment by alexfornuto** [comment] 2019-08-14 15:33
This is caused by the same issue as #5012, and is being worked on in #5018, so I'm going to close this as a duplicate.

Thanks for reporting!

**Closed by alexfornuto** 2019-08-14 15:33 UTC
