### ISSUE TITLE
Add dynamic_entity_reference to "Drupal Modules with Known Issues"

### ISSUE THREAD

**Issue by sarahg** [pantheon-systems/documentation#6544] opened 2021-07-16 16:55 UTC
https://pantheon.io/docs/modules-known-issues

Priority: Low

## Issue Description
The [dynamic_entity_reference](https://www.drupal.org/project/dynamic_entity_reference) module uses MySQL triggers. These triggers do not persist on Pantheon after a database migration or clone from one env to another.

See these issues:
- https://www.drupal.org/project/dynamic_entity_reference/issues/2930423
- https://www.drupal.org/project/dynamic_entity_reference/issues/3004545#comment-14129079
- https://www.drupal.org/project/dynamic_entity_reference/issues/3204103

### How will this impact users?
This module will not function properly on Pantheon. It would be nice to also document that MySQL triggers in general are not available (this would probably go on the "platform considerations" doc).

**Comment by joa-pan** [comment] 2021-08-06 18:27
Closing because this is a duplicate of Issue #6545

**Closed by joa-pan** 2021-08-06 18:27 UTC
Labels: New Content
