### ISSUE TITLE
Multidev information in the Quick Start guide

### ISSUE THREAD

**Issue by jrastaban** [pantheon-systems/documentation#6428] opened 2021-05-14 22:02 UTC
Re: [Site Dashboard](https://pantheon.io/docs/guides/quickstart/next-steps/)

Priority: Low

## Issue Description

* The note called out on this page says multidev is only available for agencies. Pre-COVID this was restricted based on contract tier and not agency specific. Now with COVID it is available for everyone.

### How will this impact users?

* It will give users a better understanding of the features available to them

### Context

* The availability of Multidev shifts a lot so it is a challenge to keep these references current. Once the current blanket COVID offering ends this will need changed again to whatever is determined at that time.

## Suggested Resolution

* On the [Multidev page](https://pantheon.io/docs/multidev) there is a Note that better reflects the current state. Can we re-use that here?

**Comment by carolyn-shannon** [comment] 2021-05-19 14:59
Closed as duplicate of https://github.com/pantheon-systems/documentation/issues/6416

**Closed** 2021-05-19 14:59 UTC
Labels: New Content
