### ISSUE TITLE
WP ALL Import / Export Plugin

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#3472] opened 2018-03-16 12:54 UTC
Re: [Modules and Plugins with Known Issues](https://pantheon.io/docs/modules-plugins-known-issues/)

Priority (Medium):

## Issue Description:
The customers see that the plugin is consistently having an error *Your server terminated the import process.*
The plugin documentation only talk about checking the logs, and increasing max execution time in PHP
http://www.wpallimport.com/documentation/troubleshooting/terminated-imports/

4 reports for the month of March

## Suggested Resolution

Consider if this is something not supported in the platform and be added in the docs

**Comment by eabquina** [comment] 2018-03-22 14:37
Consider also other alternatives for this plugin

**Comment by rachelwhitton** [comment] 2018-04-24 17:05
@eabquina -- thanks for the issue, we aren't ready to pick up work on it yet. I see the issue is "_Your server terminated the import process._" but we need a confirmed, tested resolution prior to taking action in docs. 

Moving this to "considered" label while the resolution gets fully flushed out. Keeping you assigned so you can circle. We may close at a later date if additional information is not provided.

**Comment by rachelwhitton** [comment] 2018-06-22 15:34
Noting client request to provide solution/workaround for this plugin (reported internally by Shayan)

**Comment by carl-alberto** [comment] 2018-08-25 23:56
Also getting chats once in a awhile from customers hitting this roadblock too and asking for a good alternative solution in doing custom imports..

**Comment by BizEvolv** [comment] 2018-10-05 15:00
I have tested this and have it working fine,  as long as I split the CSV import file into no more than 1,000 records per file... and have the WP All Import settings  set to only process 2 records per iteration,  and split into 10 chunks.

**Comment by alexfornuto** [comment] 2018-10-05 16:49
Reminder to @eabquina that this issue is held pending a proper "resolution".

In general, this issue doesn't specify if we're talking about a specific plugin or a general issue with plugins of a certain type, or that perform a certain function.

**Closed** 2018-10-31 15:41 UTC
Labels: CSE, new content, technical review

**Comment by digitalsparky** [comment] 2018-10-31 15:52
Hi folks, I've found that in the latest version it crashes with a similar issue, however, found that it was caused by an orphaned variation.

By wrapping 774 and 777 in wp-all-export/libraries/XmlExportWooCommerce.php in a try catch that returns false on exception it got around the error.

**Comment by boywondercreative** [comment] 2019-05-26 08:59
First off, let me start by saying I love everything about Pantheon. My chief complaint about clients is they would rather use HostGator then spring for enterprise-level hosting w/ Pantheon. 

That said, it's a reasonable expectation for a site running on enterprise-level hosting to be able to run an import w/o having to worry timing out .

I don't see how this can be a closed issue w/ the solution being "process 2 records per iteration". 
I can do that on cheap hosting. 

I know you guys are busy doing cool things (all of which I appreciate), but I'm sure this is a common issue. 

@louisreingold is excellent about working with different vendors to offer the best experience possible. I don't know him personally, but from what I've seen, I'm sure he'd be open to helping out.

Can we at least talk about possible solutions befitting of Pantheon?

**Comment by fakingfantastic** [comment] 2020-03-09 16:42
I just want to really emphasis exactly what @boywondercreative said. The hosting for Pantheon is rock-solid for traditional WP/Drupal needs, and what you offer works consistently and reliably. I also understand that, like with any service provider, you need to hit the 80% use case mark, but if you are going to restrict the use of a plugin that most of the lower grade hosting solutions offer, I think you have to clear offer an alternative. It makes navigating the value incentive of being an Agency Partner complicated when a client says "but I can do think on [insert hosting provider] and it costs a lot less".

Hope your team can offer some more clarity here - thanks!

**Comment by tripflex** [comment] 2020-03-31 14:42
I completely agree -- for how much we pay for Elite "enterprise" hosting -- not having the ability to be able to import large files is ridiculous.   The support response to my questions regarding this was also inadequate and I felt like I might as well be using a cheap $5/m hosting service based on the support ... at least with that $5 hosting service I can run a large import.  

**HOW IS THIS ISSUE CLOSED?**

**Comment by alesub** [comment] 2021-02-04 23:22
This is still a problem in 2021. For complex posts with several ACF fields, there are no settings possible to make the import of a single post. This is not a problem on other hosting platforms such as Pagely or SiteGround.
