### ISSUE TITLE
Network Solutions Domain Configuration Doc Update 

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#6009] opened 2020-09-23 23:20 UTC
Re: [Network Solutions Domain Configuration](https://pantheon.io/docs//network-solutions)

Priority: Low

## Issue Description:
- Links in  Adding an IPv6 record - http://www.networksolutions.com/support/Adding-an-IPv6-record/ seems to be outdated
- Network Solutions is also looking for the **host name of the name server(s)**

## Suggested Resolution
- Not sure if this is correct updated link https://knowledge.web.com/subjects/article/KA-01100/en-us#NS
- Add how to get the host name, maybe something like live-example.pantheonsite.io

**Comment by alexfornuto** [comment] 2020-09-28 15:16
Duplicate of #5968, but with good additional ideas.

**Closed by alexfornuto** 2020-09-28 15:16 UTC
Labels: Fix Content, Pantheor

**Comment by alisonjo315** [comment] 2020-10-16 21:40
@carl-alberto FYI these changes were made in #6056 -- and there's a comment from @alexfornuto on the PR thread related to what you wondered about adding a note re: how to get the host name.  Just wanted to let you know!
