### ISSUE TITLE
The Pantheon.yml Configuration File Doc Update 

### ISSUE THREAD

**Issue by primerg** [pantheon-systems/documentation#4960] opened 2019-07-31 11:14 UTC
Re: [The Pantheon.yml Configuration File](https://pantheon.io/docs/videos/pantheon-yml/)

Priority: Low

## Issue Description:
Reported Technical SEO Problem
Missing author image - https://pantheon.io/sites/default/files/styles/540x540_top/public/David_Needham540x540.png

## Suggested Resolution
Replace author image

**Comment by EdwardAngert** [comment] 2019-08-02 18:23
duplicate of #4959

**Closed by EdwardAngert** 2019-08-02 18:23 UTC
