### ISSUE TITLE
Platform and Custom Domains Doc Update 

### ISSUE THREAD

**Issue by joshualieb** [pantheon-systems/documentation#4417] opened 2019-01-24 17:54 UTC
Re: [Platform and Custom Domains](https://pantheon.io/docs/domains/)

Priority: Medium

## Issue Description:
Screenshots show separate domain and https tools, but these are legacy and should rarely show up for new sites (if at all) 

## Suggested Resolution
Replace screenshots and check associated instructions to ensure that they are accurate.

**Comment by xq42** [comment] 2019-02-06 20:34
Duplicate of this issue:

https://github.com/pantheon-systems/documentation/issues/4142

**Closed by xq42** 2019-02-06 20:34 UTC
