### ISSUE TITLE
External Libraries on Pantheon Doc Update

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#2047] opened 2016-12-21 10:23 UTC
Re: [External Libraries on Pantheon](https://pantheon.io/docs/external-libraries)
## Issue Description:
Need for separate page on feature requests:

Whenever I have a feature request, I link to this page and tell the customer that this page refers to external libraries, but the process works the same regardless.
 
## Suggested Resolution 
Would be great to split out the part on feature requests into a general "Feature requests on Pantheon" page.

**Comment by alexfornuto** [comment] 2017-05-11 15:23
Duplicate of #2402

**Closed by alexfornuto** 2017-05-11 15:23 UTC
Labels: new doc, triage
