### ISSUE TITLE
Billing in the Site Dashboard Doc: Transferring Launched/Live Sites without Removing a Card

### ISSUE THREAD

**Issue by thomas-thackery** [pantheon-systems/documentation#4437] opened 2019-02-01 19:22 UTC
Re: [Billing in the Site Dashboard](https://pantheon.io/docs/site-billing/)

Priority: High

## Issue Description:
```If a credit card is already associated with the site, site ownership can not be transferred.```
This statement is confusing and gives the impression that a site cannot be transferred unless a card is removed from a site. 

## Suggested Resolution
Customers need a clear how-to for transferring a _launched/live_ site; removing a credit card will not be the way to go since it would bring the site down.

**Comment by alexfornuto** [comment] 2019-02-05 00:13
duplicate of #4430

**Closed by alexfornuto** 2019-02-05 00:13 UTC
