### ISSUE TITLE
Create a New CMS Site Doc Update 

### ISSUE THREAD

**Issue by jpro2222** [pantheon-systems/documentation#9268] opened 2024-10-17 00:39 UTC
Re: [Create a New CMS Site](https://docs.pantheon.ioadd-site-dashboard)

Priority: High 

## Suggested Resolution: Either correct the workflow (preferable) or correct the documentation. Documentation should reflect the actual available workflow.

**Comment by rachelwhitton** [comment] 2024-10-17 15:47
Thanks for reporting! I'm closing this out as a duplicate of #9267

**Closed by rachelwhitton** 2024-10-17 15:47 UTC
