### ISSUE TITLE
Terminus Manual Doc Update org:people:list

### ISSUE THREAD

**Issue by CdrMarks** [pantheon-systems/documentation#6665] opened 2021-09-08 22:55 UTC
Re: [Terminus Manual](https://pantheon.io/docs/terminus/commands/org-people-list)

Priority: Low

## Issue Description:
A user pointed out in Slack that the `--filter` option wasn't visible on the docs site. 
Slack: [thread](https://pantheon-community.slack.com/archives/C57J1MUEM/p1631134994016000?thread_ts=1631130554.014500&cid=C57J1MUEM) 

## Suggested Resolution
Unsure as I am not sure how the options list for that command is populated.

**Comment by EdwardAngert** [comment] 2021-09-10 19:24
for Docs: we're going to try to have Terminus do Help in a way that's easier for us to include. In the meantime, we can include a partial that explains `--filter` pretty easily

**Comment by EdwardAngert** [comment] 2021-09-10 20:48
I ran `terminus list` to output into xml ([gist here](https://gist.github.com/EdwardAngert/2d4c437748b1e154cfc92cf45382278a)):

```
php /usr/local/bin/terminus list --format=xml > ~/Desktop/terminus-commands.xml
```

because I think that's similar to how the documentation is built for Terminus commands, but I don't see anything in the result that talks about `--filter` and what other commands will accept that option, but when I run `terminus org:people:list --help`, it's there 🙁 

we can still put this info into a partial for this specific command, and work with @stovak towards making future Terminus help a component that's easier to scrape into the docs

current [Terminus documentation](https://pantheon.io/docs/terminus/updates) is stuck on `2.5.0`

fwiw:
```
$ terminus --version
  Terminus 2.6.1
```

**Comment by EdwardAngert** [comment] 2021-09-15 14:11
relates to [Terminus issue #2006](https://github.com/pantheon-systems/terminus/issues/2006)

**Comment by EdwardAngert** [comment] 2022-02-01 02:16
this might be installation-specific (though, shouln't be a difference)
duplicate of issue https://github.com/pantheon-systems/terminus/issues/2038 in Terminus repo

**Closed by EdwardAngert** 2022-02-01 02:16 UTC
Labels: help wanted, Pantheor, Low Priority
