### ISSUE TITLE
New Doc Proposal: Overview of distributions publicly available on Pantheon

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#1630] opened 2016-05-30 13:24 UTC
## Title
Distributions on Pantheon

## Description
Description and logo for each, links to D.O. page and issue queues.

## Expected Audience
Customers and CSE alike

**Comment by rachelwhitton** [comment] 2016-05-31 16:14
Thanks @tinefin! Closing this one as duplicate of #1608 
 PR #1618 currently in progress.

**Closed by rachelwhitton** 2016-05-31 16:14 UTC
