### ISSUE TITLE
Search is indexing with marketing queries

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/documentation#1949] opened 2016-10-25 00:09 UTC
From the search page: https://pantheon.io/docs/search/?term=ssh+key you will see results including https://pantheon.io/docs/ssh-keys/?dtl=Tuts&utm_medium=Online%20Advertising&utm_campaign=2016%20Tuts%20Tutorial

I don't think those UTM params should be there. I suspect that the reason for this is that our docs pages don't specify canonical URLs: https://moz.com/blog/canonical-url-tag-the-most-important-advancement-in-seo-practices-since-sitemaps

**Comment by rachelwhitton** [comment] 2016-11-14 16:54
Hmm, I'm not able to reproduce this error now @stevector. I'll keep an eye out, but closing for now. Thanks!

**Comment by stevector** [comment] 2016-11-23 18:29
I'm seeing it again here:

<img width="1188" alt="screen shot 2016-11-23 at 12 27 23 pm" src="https://cloud.githubusercontent.com/assets/211029/20574049/50e13888-b178-11e6-9a8c-7b40fd439d1b.png">

Searching for "ssh key" has the first two results as 

- https://pantheon.io/docs/ssh-keys/
- https://pantheon.io/docs/ssh-keys/?dtl=Tuts&utm_medium=Online%20Advertising&utm_campaign=2016%20Tuts%20Tutorial

**Closed** 2017-01-10 18:14 UTC
Labels: review
