### ISSUE TITLE
New Doc Proposal: Create services.yml file on D8

### ISSUE THREAD

**Issue by greg-1-anderson** [pantheon-systems/documentation#934] opened 2015-09-15 20:06 UTC
See pantheon-systems/drops-8#26.

**Comment by bmackinney** [comment] 2015-09-15 20:07
Duplicate of #920

**Closed by bmackinney** 2015-09-15 20:07 UTC

**Comment by greg-1-anderson** [comment] 2015-09-15 20:08
Sorry -- didn't see the other issue, and GitHub did not create a cross-link.  Hm.

**Comment by greg-1-anderson** [comment] 2015-09-15 20:08
The cross-link was there -- user blindness error.
