### ISSUE TITLE
Document BigPipe support

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/documentation#1418] opened 2016-03-02 15:26 UTC
Re: https://www.drupal.org/node/2469431

## Issue Description

BigPipe has been committed to Drupal 8.1.x. To my knowledge, we do not yet support the Varnish change needed to use it: https://groups.google.com/a/pantheon.io/forum/#!searchin/power-users/bigpipe/power-users/3PS2CYGVavM/CBXLGxkxBQAJ

Once we add support for BigPipe we will need some kind of documentation for it. Either a new page or perhaps an addition to https://pantheon.io/docs/articles/drupal/drupal-performance-and-caching-settings/

## Suggested Resolution

Work with our engineer team to test and document BigPipe usage on Pantheon.

**Comment by bmackinney** [comment] 2016-03-02 15:52
Thank you @stevector. See https://github.com/pantheon-cookbooks/varnish/issues/23 for current eng state. The issue is active with alchemy and the patch will hopefully go live when or before 8.1.0 releases.

**Comment by rachelwhitton** [comment] 2016-05-11 22:12
Closed by #1591

**Closed by rachelwhitton** 2016-05-11 22:12 UTC
Labels: blocked, new content, product
