### ISSUE TITLE
Modules and Plugins with Known Issues Doc Update - Unloq

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#2998] opened 2017-10-16 05:18 UTC
Re: [Modules and Plugins with Known Issues](https://pantheon.io/docs/unsupported-modules-plugins/)

Priority (Medium):

## Issue Description:
The customer is going to use https://wordpress.org/plugins/unloq/ for its 2FA features. When we activate the plugin it wants us to ensure that .htaccess is writeable.

## Suggested Resolution 

Add as a new section as unsupported and highlight the 2FA docs guide (/docs/guides/two-factor-authentication)

**Comment by alexfornuto** [comment] 2017-10-17 20:52
@eabquina before saying this plugin isn't recommended, is there any way to see what restrictions it's trying to create with `.htaccess`, and offer solutions [using PHP](https://pantheon.io/docs/htaccess/)? If that were the case, could users safely ignore the warning message?

**Comment by eabquina** [comment] 2017-10-18 11:17
@alexfornuto I tried to set-up my a test site and was able to make it work eventually but came across a few issues first: 

- Did not encounter .htaccess error at all. It is possible that other plugins may affect the site
- It requires WP Native PHP Sessions plugin
- Activating directly in DEV and cloning database to will cause an error:
`An error occurred. This widget does not work on this domain`

It turns out, the Plugin writes a config in wp_options "unloq_credentials" where the API key is stored. There is no Dashboard/Admin UI field to set this up.

Customers might need to check how to actually pair an Application (1 app per domain) in UNLOQ dashboard manually to the WordPress environment.

Updating the PR to point these comments.

**Comment by chinciusan** [comment] 2017-10-18 11:47
Hi @eabquina and @alexfornuto,

I'm with the UNLOQ team. We did manage to reproduce the issue with the .htaccess file. The .htaccess file was used to add a rewrite condition for the UNLOQ custom login path (/unloq). However, when the .htaccess was not writable, a warning was displayed, but the UNLOQ login path was still accessible (using /?unloq).
We will be releasing a patch shortly to address this issue.

@eabquina the UNLOQ plugin (used in wp-login.php and NOT in /unloq) was designed to work on a single domain. When you cloned the database, the API credentials were used, however I would guess that you changed the domain of the site, hence the login widget refusing to load on a different domain. This feature is intentional.
Since the API credentials are not something that are to be used publicly, we chose not to display them anywhere.

**Comment by rachelwhitton** [comment] 2017-10-19 20:09
Thanks @chinciusan! We documented API credentials in #2999, leaving this issue open to continue evaluation the .htaccess scenario / test patch

**Comment by rachelwhitton** [comment] 2018-01-08 19:35
Checking back in on this @chinciusan - was the patch released?

**Comment by chinciusan** [comment] 2018-01-09 10:03
Yes it was. The newer versions of UNLOQ plugin shouldn't have any issues. But feel free to test on your environments.

**Comment by alexfornuto** [comment] 2018-01-09 22:07
@chinciusan Thanks for following up! I'm testing the plugin, but unable to copy settings from one environment to another:

<img width="497" alt="screen shot 2018-01-09 at 4 40 47 pm" src="https://user-images.githubusercontent.com/2349184/34745004-27161968-f55d-11e7-8049-f09161b8a049.png">

Under settings, Unloq shows the new environment's domain under "Login pages", but still seems to be trying to use the previous domain. 

If the solution is to just reconfigure for each domain, then so be it, I just thought I'd run it by you first.

**Comment by chinciusan** [comment] 2018-01-10 08:42
@alexfornuto yes this is the normal behaviour. Copying settings shouldn't work, as the first domain, used to create the widget, was saved on our end, so when the widget is loaded on a different domain it should throw that error. If you just don't want to create a different widget for your app (WP site) you can change the domain, by logging into https://account.unloq.io/ , go to your application's settings -> widget and edit the domain name there. 
![screen shot 2018-01-10 at 10 41 03](https://user-images.githubusercontent.com/5501918/34763167-d157b72a-f5f2-11e7-8618-1afb644b486b.jpg)

**Comment by alexfornuto** [comment] 2018-01-10 15:30
Thanks @chinciusan! Sounds like the current explanation of the issue [here](https://pantheon.io/docs/unsupported-modules-plugins/#unloq-two-factor-authentication-2fa) is accurate, and we can close the issue.

**Closed by alexfornuto** 2018-01-10 15:30 UTC
Labels: CSE, blocked, new content
