### ISSUE TITLE
Pantheon Localdev Doc Update 

### ISSUE THREAD

**Issue by XjSv** [pantheon-systems/documentation#6933] opened 2021-12-16 15:47 UTC
Re: [Pantheon Localdev](https://pantheon.io/docs//guides/localdev/changelog)

Priority: Low

## Issue Description
There is no change log for the edge channel updates. It would be helpful to know what is the latest supported docker version and what has changed.

## Suggested Resolution
Include the change log for the edge channel updates.

**Comment by EdwardAngert** [comment] 2021-12-16 17:15
thanks, @XjSv !
this is a long-standing issue that we're trying to work on as part of a larger improvement to the docs site

closing this issue for now as a duplicate of #6380

**Closed by EdwardAngert** 2021-12-16 17:15 UTC
Labels: Fix Content
