### ISSUE TITLE
Accessing MySQL Databases Doc Update 

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#3839] opened 2018-06-29 13:22 UTC
Re: [Accessing MySQL Databases](https://pantheon.io/docs/mysql-access/)

Priority: High

## Issue Description:

We currently have around 10 tickets and numerous chats from people having DB connection issues.
At least part of the problem seems to be outdated openssl version, not supporting TLSv1.2. 
Pantheon does not support TLSv1.1 for security reasons.

The error message received will be:
`SSL connection error: unknown error number`

## Suggested Resolution

Could we add a troubleshooting section on this error + how to update openssl on Mac / Windows ?
v1.0.1 and above supports TLSv1.2.

On Mac, using brew to update will work.

**Comment by alexfornuto** [comment] 2018-06-29 13:53
@tinefin how _does_ one update OpenSSL on Windows? And for Mac, using brew works if you already have brew, and the openssl package provided by brew.

**Comment by alexfornuto** [comment] 2018-06-29 15:41
Closing as a duplicate of #3802

**Comment by tinefin** [comment] 2018-07-01 23:58
@alexfornuto Please don't close this. The other issue is about CA certs, which is a very different thing. Plus we have quite a few users having this issue.

**Comment by alexfornuto** [comment] 2018-07-19 16:40
Resolved in BUGS-2075

**Closed by alexfornuto** 2018-07-19 16:40 UTC
Labels: CSE, blocked
