### ISSUE TITLE
Pantheon Secrets Guide Doc Update 

### ISSUE THREAD

**Issue by kirk-brown-ew** [pantheon-systems/documentation#9285] opened 2024-10-30 14:12 UTC
Re: [Pantheon Secrets Guide](https://docs.pantheon.io/guides/secrets/local)

Priority: Low/Medium/High (choose one, remove the other options)

I have a documentation updates for the Pantheon Secrets local development page (https://docs.pantheon.io/guides/secrets/local):
- The terminus command to generate the secrets.json file requires a <site> parameter.
- The secrets.json file updates for values is not as clear as it could be.  I've found filling in the "Value" and "EnvValues"."live" values worked.
- In the DDev configuration file, I ended up using the full path within the container to get the secrets.json file to be recognized: "- CUSTOMER_SECRETS_FAKE_FILE=/var/www/html/secrets.json".

**Comment by rachelwhitton** [comment] 2024-10-30 15:51
Potential dupe of #9233 assigning to @jazzsequence to review

**Closed** 2024-11-25 22:43 UTC
Labels: Type: Fix Content, Topic: Secrets
