### ISSUE TITLE
New Doc Proposal: ClamAV

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#2780] opened 2017-08-14 19:21 UTC
Priority (Low‚ Medium‚ High): Low

## Title
Enabling ClamAV with WordPress or Drupal

## Description
Scan for malware and other potential threats in Wordpress or Drupal using ClamAV, an open source antivirus engine.

## Outline
Intro / summary of why
WordPress
Drupal 7 & 8 
Conclusion

## Path
`source/_docs/clamav.md` 

Refer to config suggested in chat 11261049093 cc @newtoid

**Comment by alexfornuto** [comment] 2017-09-07 02:28
Closing as a duplicate of #1913

**Closed by alexfornuto** 2017-09-07 02:28 UTC
Labels: new doc, triage
