### ISSUE TITLE
Automated Testing for WordPress with Behat Doc Update  : Issue in maitaining updates

### ISSUE THREAD

**Issue by sagarsarkar** [pantheon-systems/documentation#2472] opened 2017-05-15 04:35 UTC
Re: [Automated Testing for WordPress with Behat](https://pantheon.io/docs/guides/wordpress-automated-testing/)

Priority (High):

## Issue Description: I have installed more than 6-7 times. Behat, Mink all gets installed. But i faced issues with deprecated version of Symfony. Even once I fix those issues, I had faced php fatal error.
Can you please help?

## Suggested Resolution

**Comment by greg-1-anderson** [comment] 2017-05-15 15:53
Duplicate of #2469

**Closed by greg-1-anderson** 2017-05-15 15:53 UTC
